name: Node.js CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main'
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm ci
      - name: Running tests
        run: npm run test --coverage

  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.11.0
        uses: actions/setup-node@v2
        with:
          node-version: 16.11.0
      - run: npm ci
      - run: npm run build --if-present
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "ismile-api"
          heroku_email: ${{secrets.HEROKU_API_EMAIL}}
